// Dashboard.styles.ts
import { BACKGROUND_COLOR, PRIMARY_COLOR } from "@/constants/constants";
import { Platform, StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  scrollContainer: {
    paddingBottom: 120,
    backgroundColor: BACKGROUND_COLOR,
  },
  welcomeBanner: {
    marginHorizontal: 16,
    marginBottom: 20,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E8EAEF",
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.06,
        shadowRadius: 14,
      },
      android: { elevation: 2 },
    }),
  },
  welcomeHeroRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  welcomeTextCol: {
    flex: 1,
    minWidth: 0,
  },
  welcomeEyebrow: {
    fontSize: 12,
    color: PRIMARY_COLOR,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  welcomeTitle: {
    fontSize: 22,
    color: "#111827",
    marginBottom: 6,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 20,
  },
  horizontalScroll: {
    padding: 0,
    flexDirection: "row",
    paddingBottom: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 28,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 17,
    color: "#111827",
    letterSpacing: -0.2,
  },
  sectionHint: {
    fontSize: 13,
    color: "#9CA3AF",
    paddingHorizontal: 16,
    marginTop: -4,
    marginBottom: 12,
  },
  cardChart: {
    backgroundColor: BACKGROUND_COLOR,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 0,
  },
  chartCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingTop: 40,
    paddingBottom: 4,
    borderWidth: 1,
    borderColor: "#ECECF0",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.07,
        shadowRadius: 20,
      },
      android: { elevation: 3 },
    }),
  },
  chartWrapper: {
    alignItems: "center",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 20,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#ECECF0",
    width: 300,
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
      },
      android: { elevation: 3 },
    }),
  },
  cardTitle: {
    fontSize: 16,
    color: "#111827",
    marginBottom: 14,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#E5E7EB",
    marginBottom: 14,
  },
  emptyWrap: {
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  emptyIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 15,
    color: "#374151",
    textAlign: "center",
    marginBottom: 4,
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#9CA3AF",
    textAlign: "center",
    lineHeight: 18,
  },
  eventRow: {
    marginBottom: 14,
  },
  eventTitle: {
    fontSize: 14,
    color: "#1F2937",
    marginBottom: 4,
  },
  eventTime: {
    fontSize: 13,
    color: "#6B7280",
  },
  fabContainer: {
    position: "absolute",
    bottom: 120,
    right: 20,
    alignItems: "center",
  },
  fab: {
    backgroundColor: PRIMARY_COLOR,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  subFab: {
    position: "absolute",
    bottom: 0,
    right: 0,
  },
  fabButton: {
    backgroundColor: PRIMARY_COLOR,
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
});
